import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { API } from './const/api'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {Object.keys(API).map(key => (<Link href={`/rss2?key=${key}`} key={key}><a className={styles.card}>{key}</a></Link>))}
        </div>
      </main>
    </div>
  )
}

export default Home
